name: Docker CI

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github registry
        uses: docker/login-action@v1 
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/pjatk21/alt-scrap:latest
            ghcr.io/pjatk21/alt-scrap:${{github.ref_name}}
